const salmos = [
  { referencia: "Salmo 1:1-3", texto: "Comece o dia escolhendo caminhos que produzam bons frutos." },
  { referencia: "Salmo 2:12", texto: "Confie em Deus e encontre segurança nele." },
  { referencia: "Salmo 3:3", texto: "Deus pode ser seu escudo e sua força neste dia." },
  { referencia: "Salmo 4:8", texto: "Descanse em paz, sabendo que Deus cuida de você." },
  { referencia: "Salmo 5:11", texto: "Alegre-se na proteção e na bondade do Senhor." },
  { referencia: "Salmo 6:9", texto: "Deus ouve a oração sincera." },
  { referencia: "Salmo 7:10", texto: "Entregue sua causa a Deus e siga com confiança." },
  { referencia: "Salmo 8:3-4", texto: "Contemple a grandeza de Deus e lembre-se do seu valor." },
  { referencia: "Salmo 9:1-2", texto: "Agradeça pelas coisas boas que Deus já fez." },
  { referencia: "Salmo 10:17", texto: "Deus escuta os desejos de um coração humilde." },
  { referencia: "Salmo 11:7", texto: "Busque viver com justiça e integridade." },
  { referencia: "Salmo 12:6", texto: "A palavra de Deus é firme e confiável." },
  { referencia: "Salmo 13:5-6", texto: "Mesmo em dias difíceis, mantenha a confiança no amor de Deus." },
  { referencia: "Salmo 14:7", texto: "Espere pela restauração que vem do Senhor." },
  { referencia: "Salmo 15:1-2", texto: "Viva com sinceridade e pratique o que é correto." },
  { referencia: "Salmo 16:8", texto: "Mantenha Deus diante de você em cada decisão." },
  { referencia: "Salmo 17:8", texto: "Peça proteção e cuidado para o seu caminho." },
  { referencia: "Salmo 18:2", texto: "Faça de Deus seu refúgio e sua fortaleza." },
  { referencia: "Salmo 19:1", texto: "Veja a criação como sinal da grandeza de Deus." },
  { referencia: "Salmo 20:7", texto: "Não coloque sua confiança apenas nas coisas humanas." },
  { referencia: "Salmo 21:7", texto: "Quem confia em Deus encontra firmeza." },
  { referencia: "Salmo 22:26", texto: "Busque a Deus com humildade e gratidão." },
  { referencia: "Salmo 23:1", texto: "Deixe Deus conduzir cada necessidade do seu dia." },
  { referencia: "Salmo 24:1", texto: "Lembre-se de que tudo pertence ao Senhor." },
  { referencia: "Salmo 25:4-5", texto: "Peça direção e disposição para aprender os caminhos de Deus." },
  { referencia: "Salmo 26:3", texto: "Mantenha os olhos na fidelidade de Deus." },
  { referencia: "Salmo 27:1", texto: "Quando o medo aparecer, lembre-se de que Deus é luz." },
  { referencia: "Salmo 28:7", texto: "Fortaleça o coração confiando no Senhor." },
  { referencia: "Salmo 29:11", texto: "Receba a paz que Deus oferece." },
  { referencia: "Salmo 30:5", texto: "Depois da noite, a alegria pode voltar." },
  { referencia: "Salmo 31:24", texto: "Tenha coragem e mantenha a esperança." },
  { referencia: "Salmo 32:8", texto: "Deixe Deus orientar suas escolhas." },
  { referencia: "Salmo 33:20-22", texto: "Espere em Deus com confiança e gratidão." },
  { referencia: "Salmo 34:8", texto: "Experimente a bondade de Deus nas pequenas coisas." },
  { referencia: "Salmo 35:9", texto: "Faça de Deus a fonte da sua alegria." },
  { referencia: "Salmo 36:7", texto: "Acolha-se no amor e na misericórdia de Deus." },
  { referencia: "Salmo 37:5", texto: "Entregue seus planos ao Senhor e continue fazendo o bem." },
  { referencia: "Salmo 38:15", texto: "Mesmo esperando, mantenha sua esperança em Deus." },
  { referencia: "Salmo 39:7", texto: "Pergunte a si mesmo onde está sua verdadeira esperança." },
  { referencia: "Salmo 40:1", texto: "Espere com paciência; Deus não ignora sua oração." },
  { referencia: "Salmo 41:1", texto: "Pratique generosidade com quem precisa." },
  { referencia: "Salmo 42:11", texto: "Quando estiver abatido, volte a colocar sua esperança em Deus." },
  { referencia: "Salmo 43:3", texto: "Peça luz para enxergar o caminho correto." },
  { referencia: "Salmo 44:8", texto: "Que sua alegria esteja em Deus, não apenas nas circunstâncias." },
  { referencia: "Salmo 45:1", texto: "Use suas palavras para transmitir aquilo que é bom." },
  { referencia: "Salmo 46:1", texto: "Em tempos de dificuldade, Deus é um refúgio presente." },
  { referencia: "Salmo 47:1", texto: "Celebre com alegria as vitórias e bênçãos." },
  { referencia: "Salmo 48:14", texto: "Lembre-se de que Deus permanece presente em cada fase da vida." },
  { referencia: "Salmo 49:15", texto: "Confie que Deus pode resgatar e sustentar você." },
  { referencia: "Salmo 50:15", texto: "Clame a Deus quando precisar de ajuda." },
  { referencia: "Salmo 51:10", texto: "Peça um coração renovado e disposto a recomeçar." },
  { referencia: "Salmo 52:8", texto: "Permaneça firme como quem está plantado em Deus." },
  { referencia: "Salmo 53:6", texto: "Espere pela salvação e pela restauração do Senhor." },
  { referencia: "Salmo 54:4", texto: "Lembre-se de que Deus sustenta você." },
  { referencia: "Salmo 55:22", texto: "Entregue suas preocupações a Deus e não carregue tudo sozinho." },
  { referencia: "Salmo 56:3", texto: "Quando o medo vier, escolha confiar." },
  { referencia: "Salmo 57:7", texto: "Fortaleça seu coração antes de enfrentar os desafios." },
  { referencia: "Salmo 58:11", texto: "Continue fazendo o bem mesmo quando parecer difícil." },
  { referencia: "Salmo 59:16", texto: "Comece e termine o dia lembrando da fidelidade de Deus." },
  { referencia: "Salmo 60:12", texto: "Com Deus, você pode avançar com coragem." },
  { referencia: "Salmo 61:2-3", texto: "Quando estiver longe ou cansado, busque abrigo em Deus." },
  { referencia: "Salmo 62:1-2", texto: "Descanse em Deus antes de procurar respostas em todo lugar." },
  { referencia: "Salmo 63:1", texto: "Procure Deus com sede e sinceridade." },
  { referencia: "Salmo 64:10", texto: "Alegre-se em Deus e escolha viver com retidão." },
  { referencia: "Salmo 65:11", texto: "Reconheça as bênçãos que chegam ao longo do ano." },
  { referencia: "Salmo 66:20", texto: "Agradeça porque Deus ouve a oração." },
  { referencia: "Salmo 67:1", texto: "Peça que a graça de Deus acompanhe seu dia." },
  { referencia: "Salmo 68:19", texto: "Reconheça o peso que Deus já ajudou você a carregar." },
  { referencia: "Salmo 69:30", texto: "Escolha louvar a Deus mesmo em meio às lutas." },
  { referencia: "Salmo 70:4", texto: "Que quem busca Deus encontre alegria." },
  { referencia: "Salmo 71:5", texto: "Faça da esperança em Deus sua âncora." },
  { referencia: "Salmo 72:18", texto: "Lembre-se das obras de Deus e agradeça." },
  { referencia: "Salmo 73:26", texto: "Mesmo quando faltar força, Deus pode ser sua porção." },
  { referencia: "Salmo 74:12", texto: "Confie que Deus continua agindo na história." },
  { referencia: "Salmo 75:1", texto: "Agradeça por tudo o que Deus já fez." },
  { referencia: "Salmo 76:11", texto: "Cumpra seus compromissos com sinceridade." },
  { referencia: "Salmo 77:11", texto: "Recorde as obras de Deus e fortaleça sua fé." },
  { referencia: "Salmo 78:4", texto: "Compartilhe com outros aquilo que Deus tem feito." },
  { referencia: "Salmo 79:13", texto: "Seja grato pelo cuidado constante de Deus." },
  { referencia: "Salmo 80:3", texto: "Peça restauração quando sentir que se afastou." },
  { referencia: "Salmo 81:10", texto: "Receba de Deus aquilo que alimenta e fortalece sua vida." },
  { referencia: "Salmo 82:8", texto: "Reconheça que Deus governa com justiça." },
  { referencia: "Salmo 83:18", texto: "Que todos conheçam a grandeza do Senhor." },
  { referencia: "Salmo 84:11", texto: "Deus oferece graça e proteção aos que caminham com ele." },
  { referencia: "Salmo 85:10", texto: "Busque reconciliação, verdade e paz." },
  { referencia: "Salmo 86:5", texto: "Confie na bondade e no perdão de Deus." },
  { referencia: "Salmo 87:7", texto: "Encontre alegria nas fontes que Deus colocou em sua vida." },
  { referencia: "Salmo 88:13", texto: "Mesmo na aflição, continue orando." },
  { referencia: "Salmo 89:1", texto: "Declare a fidelidade de Deus com suas atitudes." },
  { referencia: "Salmo 90:12", texto: "Valorize bem o tempo que você recebeu." },
  { referencia: "Salmo 91:1-2", texto: "Faça de Deus sua morada e seu abrigo." },
  { referencia: "Salmo 92:1-2", texto: "Comece o dia agradecendo pela bondade e fidelidade de Deus." },
  { referencia: "Salmo 93:1", texto: "Lembre-se de que Deus reina acima das circunstâncias." },
  { referencia: "Salmo 94:19", texto: "Quando os pensamentos se multiplicarem, busque consolo em Deus." },
  { referencia: "Salmo 95:1", texto: "Convide seu coração a adorar com alegria." },
  { referencia: "Salmo 96:3", texto: "Conte às pessoas as coisas boas que Deus tem feito." },
  { referencia: "Salmo 97:11", texto: "Espere pela luz mesmo nos dias escuros." },
  { referencia: "Salmo 98:4", texto: "Celebre a Deus com alegria." },
  { referencia: "Salmo 99:5", texto: "Adore com respeito e gratidão." },
  { referencia: "Salmo 100:2", texto: "Sirva a Deus com alegria." },
  { referencia: "Salmo 101:2", texto: "Escolha viver de modo íntegro dentro e fora de casa." },
  { referencia: "Salmo 102:17", texto: "Deus presta atenção à oração de quem necessita." },
  { referencia: "Salmo 103:2-5", texto: "Não se esqueça dos benefícios e cuidados de Deus." },
  { referencia: "Salmo 104:24", texto: "Admire a sabedoria de Deus presente na criação." },
  { referencia: "Salmo 105:4", texto: "Busque força em Deus continuamente." },
  { referencia: "Salmo 106:1", texto: "Agradeça porque a bondade de Deus não acaba." },
  { referencia: "Salmo 107:1", texto: "Reconheça o amor constante do Senhor." },
  { referencia: "Salmo 108:1", texto: "Tenha um coração firme para louvar." },
  { referencia: "Salmo 109:30", texto: "Expresse gratidão publicamente." },
  { referencia: "Salmo 110:1", texto: "Lembre-se de que Deus tem autoridade sobre tudo." },
  { referencia: "Salmo 111:10", texto: "A verdadeira sabedoria começa com reverência a Deus." },
  { referencia: "Salmo 112:7", texto: "Não viva dominado pelo medo de más notícias." },
  { referencia: "Salmo 113:3", texto: "Louve a Deus em todos os momentos do dia." },
  { referencia: "Salmo 114:7", texto: "Respeite a presença e o poder de Deus." },
  { referencia: "Salmo 115:11", texto: "Confie no Senhor quando precisar de ajuda." },
  { referencia: "Salmo 116:1-2", texto: "Ame a Deus e fale com ele com liberdade." },
  { referencia: "Salmo 117:1-2", texto: "Compartilhe o louvor e a gratidão." },
  { referencia: "Salmo 118:24", texto: "Hoje é um presente: viva com alegria e propósito." },
  { referencia: "Salmo 119:11", texto: "Guarde os ensinamentos de Deus no coração." },
  { referencia: "Salmo 120:1", texto: "Quando estiver angustiado, ore." },
  { referencia: "Salmo 121:1-2", texto: "Levante os olhos e lembre-se de onde vem seu socorro." },
  { referencia: "Salmo 122:1", texto: "Alegre-se por poder buscar a presença de Deus." },
  { referencia: "Salmo 123:1", texto: "Olhe para Deus com expectativa." },
  { referencia: "Salmo 124:8", texto: "Lembre-se de que sua ajuda vem do Criador." },
  { referencia: "Salmo 125:1", texto: "Confie em Deus com estabilidade." },
  { referencia: "Salmo 126:3", texto: "Reconheça as grandes coisas que Deus já fez." },
  { referencia: "Salmo 127:1", texto: "Construa seus projetos com Deus no centro." },
  { referencia: "Salmo 128:1", texto: "Caminhe com reverência e gratidão." },
  { referencia: "Salmo 129:4", texto: "Confie na justiça de Deus." },
  { referencia: "Salmo 130:5", texto: "Espere no Senhor e na sua palavra." },
  { referencia: "Salmo 131:2", texto: "Busque quietude interior diante de Deus." },
  { referencia: "Salmo 132:15", texto: "Receba o cuidado e a provisão de Deus." },
  { referencia: "Salmo 133:1", texto: "Valorize a união e a paz entre as pessoas." },
  { referencia: "Salmo 134:2", texto: "Levante suas mãos e seu coração em gratidão." },
  { referencia: "Salmo 135:3", texto: "Louve porque Deus é bom." },
  { referencia: "Salmo 136:1", texto: "Agradeça porque o amor de Deus permanece." },
  { referencia: "Salmo 137:5", texto: "Não esqueça aquilo que é importante para sua fé." },
  { referencia: "Salmo 138:3", texto: "Quando clamar, espere que Deus fortaleça você." },
  { referencia: "Salmo 139:14", texto: "Agradeça pela forma única como sua vida foi criada." },
  { referencia: "Salmo 140:13", texto: "Escolha viver de modo digno e agradecido." },
  { referencia: "Salmo 141:3", texto: "Peça sabedoria para falar no momento certo." },
  { referencia: "Salmo 142:5", texto: "Faça de Deus seu refúgio." },
  { referencia: "Salmo 143:8", texto: "Peça que o amor de Deus conduza seu dia desde a manhã." },
  { referencia: "Salmo 144:1-2", texto: "Reconheça Deus como sua proteção e força." },
  { referencia: "Salmo 145:18", texto: "Busque Deus com sinceridade; ele está perto." },
  { referencia: "Salmo 146:5", texto: "Feliz é quem encontra sua esperança no Senhor." },
  { referencia: "Salmo 147:3", texto: "Deus cuida de corações feridos." },
  { referencia: "Salmo 148:13", texto: "Reconheça a grandeza do nome de Deus." },
  { referencia: "Salmo 149:4", texto: "Deus se alegra com quem busca sua vontade." },
  { referencia: "Salmo 150:6", texto: "Que tudo em você encontre motivo para louvar." },
  { referencia: "Salmo 1:1-3", texto: "Comece o dia escolhendo caminhos que produzam bons frutos." },
  { referencia: "Salmo 2:12", texto: "Confie em Deus e encontre segurança nele." },
  { referencia: "Salmo 3:3", texto: "Deus pode ser seu escudo e sua força neste dia." },
  { referencia: "Salmo 4:8", texto: "Descanse em paz, sabendo que Deus cuida de você." },
  { referencia: "Salmo 5:11", texto: "Alegre-se na proteção e na bondade do Senhor." },
  { referencia: "Salmo 6:9", texto: "Deus ouve a oração sincera." },
  { referencia: "Salmo 7:10", texto: "Entregue sua causa a Deus e siga com confiança." },
  { referencia: "Salmo 8:3-4", texto: "Contemple a grandeza de Deus e lembre-se do seu valor." },
  { referencia: "Salmo 9:1-2", texto: "Agradeça pelas coisas boas que Deus já fez." },
  { referencia: "Salmo 10:17", texto: "Deus escuta os desejos de um coração humilde." },
  { referencia: "Salmo 11:7", texto: "Busque viver com justiça e integridade." },
  { referencia: "Salmo 12:6", texto: "A palavra de Deus é firme e confiável." },
  { referencia: "Salmo 13:5-6", texto: "Mesmo em dias difíceis, mantenha a confiança no amor de Deus." },
  { referencia: "Salmo 14:7", texto: "Espere pela restauração que vem do Senhor." },
  { referencia: "Salmo 15:1-2", texto: "Viva com sinceridade e pratique o que é correto." },
  { referencia: "Salmo 16:8", texto: "Mantenha Deus diante de você em cada decisão." },
  { referencia: "Salmo 17:8", texto: "Peça proteção e cuidado para o seu caminho." },
  { referencia: "Salmo 18:2", texto: "Faça de Deus seu refúgio e sua fortaleza." },
  { referencia: "Salmo 19:1", texto: "Veja a criação como sinal da grandeza de Deus." },
  { referencia: "Salmo 20:7", texto: "Não coloque sua confiança apenas nas coisas humanas." },
  { referencia: "Salmo 21:7", texto: "Quem confia em Deus encontra firmeza." },
  { referencia: "Salmo 22:26", texto: "Busque a Deus com humildade e gratidão." },
  { referencia: "Salmo 23:1", texto: "Deixe Deus conduzir cada necessidade do seu dia." },
  { referencia: "Salmo 24:1", texto: "Lembre-se de que tudo pertence ao Senhor." },
  { referencia: "Salmo 25:4-5", texto: "Peça direção e disposição para aprender os caminhos de Deus." },
  { referencia: "Salmo 26:3", texto: "Mantenha os olhos na fidelidade de Deus." },
  { referencia: "Salmo 27:1", texto: "Quando o medo aparecer, lembre-se de que Deus é luz." },
  { referencia: "Salmo 28:7", texto: "Fortaleça o coração confiando no Senhor." },
  { referencia: "Salmo 29:11", texto: "Receba a paz que Deus oferece." },
  { referencia: "Salmo 30:5", texto: "Depois da noite, a alegria pode voltar." },
  { referencia: "Salmo 31:24", texto: "Tenha coragem e mantenha a esperança." },
  { referencia: "Salmo 32:8", texto: "Deixe Deus orientar suas escolhas." },
  { referencia: "Salmo 33:20-22", texto: "Espere em Deus com confiança e gratidão." },
  { referencia: "Salmo 34:8", texto: "Experimente a bondade de Deus nas pequenas coisas." },
  { referencia: "Salmo 35:9", texto: "Faça de Deus a fonte da sua alegria." },
  { referencia: "Salmo 36:7", texto: "Acolha-se no amor e na misericórdia de Deus." },
  { referencia: "Salmo 37:5", texto: "Entregue seus planos ao Senhor e continue fazendo o bem." },
  { referencia: "Salmo 38:15", texto: "Mesmo esperando, mantenha sua esperança em Deus." },
  { referencia: "Salmo 39:7", texto: "Pergunte a si mesmo onde está sua verdadeira esperança." },
  { referencia: "Salmo 40:1", texto: "Espere com paciência; Deus não ignora sua oração." },
  { referencia: "Salmo 41:1", texto: "Pratique generosidade com quem precisa." },
  { referencia: "Salmo 42:11", texto: "Quando estiver abatido, volte a colocar sua esperança em Deus." },
  { referencia: "Salmo 43:3", texto: "Peça luz para enxergar o caminho correto." },
  { referencia: "Salmo 44:8", texto: "Que sua alegria esteja em Deus, não apenas nas circunstâncias." },
  { referencia: "Salmo 45:1", texto: "Use suas palavras para transmitir aquilo que é bom." },
  { referencia: "Salmo 46:1", texto: "Em tempos de dificuldade, Deus é um refúgio presente." },
  { referencia: "Salmo 47:1", texto: "Celebre com alegria as vitórias e bênçãos." },
  { referencia: "Salmo 48:14", texto: "Lembre-se de que Deus permanece presente em cada fase da vida." },
  { referencia: "Salmo 49:15", texto: "Confie que Deus pode resgatar e sustentar você." },
  { referencia: "Salmo 50:15", texto: "Clame a Deus quando precisar de ajuda." },
  { referencia: "Salmo 51:10", texto: "Peça um coração renovado e disposto a recomeçar." },
  { referencia: "Salmo 52:8", texto: "Permaneça firme como quem está plantado em Deus." },
  { referencia: "Salmo 53:6", texto: "Espere pela salvação e pela restauração do Senhor." },
  { referencia: "Salmo 54:4", texto: "Lembre-se de que Deus sustenta você." },
  { referencia: "Salmo 55:22", texto: "Entregue suas preocupações a Deus e não carregue tudo sozinho." },
  { referencia: "Salmo 56:3", texto: "Quando o medo vier, escolha confiar." },
  { referencia: "Salmo 57:7", texto: "Fortaleça seu coração antes de enfrentar os desafios." },
  { referencia: "Salmo 58:11", texto: "Continue fazendo o bem mesmo quando parecer difícil." },
  { referencia: "Salmo 59:16", texto: "Comece e termine o dia lembrando da fidelidade de Deus." },
  { referencia: "Salmo 60:12", texto: "Com Deus, você pode avançar com coragem." },
  { referencia: "Salmo 61:2-3", texto: "Quando estiver longe ou cansado, busque abrigo em Deus." },
  { referencia: "Salmo 62:1-2", texto: "Descanse em Deus antes de procurar respostas em todo lugar." },
  { referencia: "Salmo 63:1", texto: "Procure Deus com sede e sinceridade." },
  { referencia: "Salmo 64:10", texto: "Alegre-se em Deus e escolha viver com retidão." },
  { referencia: "Salmo 65:11", texto: "Reconheça as bênçãos que chegam ao longo do ano." },
  { referencia: "Salmo 66:20", texto: "Agradeça porque Deus ouve a oração." },
  { referencia: "Salmo 67:1", texto: "Peça que a graça de Deus acompanhe seu dia." },
  { referencia: "Salmo 68:19", texto: "Reconheça o peso que Deus já ajudou você a carregar." },
  { referencia: "Salmo 69:30", texto: "Escolha louvar a Deus mesmo em meio às lutas." },
  { referencia: "Salmo 70:4", texto: "Que quem busca Deus encontre alegria." },
  { referencia: "Salmo 71:5", texto: "Faça da esperança em Deus sua âncora." },
  { referencia: "Salmo 72:18", texto: "Lembre-se das obras de Deus e agradeça." },
  { referencia: "Salmo 73:26", texto: "Mesmo quando faltar força, Deus pode ser sua porção." },
  { referencia: "Salmo 74:12", texto: "Confie que Deus continua agindo na história." },
  { referencia: "Salmo 75:1", texto: "Agradeça por tudo o que Deus já fez." },
  { referencia: "Salmo 76:11", texto: "Cumpra seus compromissos com sinceridade." },
  { referencia: "Salmo 77:11", texto: "Recorde as obras de Deus e fortaleça sua fé." },
  { referencia: "Salmo 78:4", texto: "Compartilhe com outros aquilo que Deus tem feito." },
  { referencia: "Salmo 79:13", texto: "Seja grato pelo cuidado constante de Deus." },
  { referencia: "Salmo 80:3", texto: "Peça restauração quando sentir que se afastou." },
  { referencia: "Salmo 81:10", texto: "Receba de Deus aquilo que alimenta e fortalece sua vida." },
  { referencia: "Salmo 82:8", texto: "Reconheça que Deus governa com justiça." },
  { referencia: "Salmo 83:18", texto: "Que todos conheçam a grandeza do Senhor." },
  { referencia: "Salmo 84:11", texto: "Deus oferece graça e proteção aos que caminham com ele." },
  { referencia: "Salmo 85:10", texto: "Busque reconciliação, verdade e paz." },
  { referencia: "Salmo 86:5", texto: "Confie na bondade e no perdão de Deus." },
  { referencia: "Salmo 87:7", texto: "Encontre alegria nas fontes que Deus colocou em sua vida." },
  { referencia: "Salmo 88:13", texto: "Mesmo na aflição, continue orando." },
  { referencia: "Salmo 89:1", texto: "Declare a fidelidade de Deus com suas atitudes." },
  { referencia: "Salmo 90:12", texto: "Valorize bem o tempo que você recebeu." },
  { referencia: "Salmo 91:1-2", texto: "Faça de Deus sua morada e seu abrigo." },
  { referencia: "Salmo 92:1-2", texto: "Comece o dia agradecendo pela bondade e fidelidade de Deus." },
  { referencia: "Salmo 93:1", texto: "Lembre-se de que Deus reina acima das circunstâncias." },
  { referencia: "Salmo 94:19", texto: "Quando os pensamentos se multiplicarem, busque consolo em Deus." },
  { referencia: "Salmo 95:1", texto: "Convide seu coração a adorar com alegria." },
  { referencia: "Salmo 96:3", texto: "Conte às pessoas as coisas boas que Deus tem feito." },
  { referencia: "Salmo 97:11", texto: "Espere pela luz mesmo nos dias escuros." },
  { referencia: "Salmo 98:4", texto: "Celebre a Deus com alegria." },
  { referencia: "Salmo 99:5", texto: "Adore com respeito e gratidão." },
  { referencia: "Salmo 100:2", texto: "Sirva a Deus com alegria." },
  { referencia: "Salmo 101:2", texto: "Escolha viver de modo íntegro dentro e fora de casa." },
  { referencia: "Salmo 102:17", texto: "Deus presta atenção à oração de quem necessita." },
  { referencia: "Salmo 103:2-5", texto: "Não se esqueça dos benefícios e cuidados de Deus." },
  { referencia: "Salmo 104:24", texto: "Admire a sabedoria de Deus presente na criação." },
  { referencia: "Salmo 105:4", texto: "Busque força em Deus continuamente." },
  { referencia: "Salmo 106:1", texto: "Agradeça porque a bondade de Deus não acaba." },
  { referencia: "Salmo 107:1", texto: "Reconheça o amor constante do Senhor." },
  { referencia: "Salmo 108:1", texto: "Tenha um coração firme para louvar." },
  { referencia: "Salmo 109:30", texto: "Expresse gratidão publicamente." },
  { referencia: "Salmo 110:1", texto: "Lembre-se de que Deus tem autoridade sobre tudo." },
  { referencia: "Salmo 111:10", texto: "A verdadeira sabedoria começa com reverência a Deus." },
  { referencia: "Salmo 112:7", texto: "Não viva dominado pelo medo de más notícias." },
  { referencia: "Salmo 113:3", texto: "Louve a Deus em todos os momentos do dia." },
  { referencia: "Salmo 114:7", texto: "Respeite a presença e o poder de Deus." },
  { referencia: "Salmo 115:11", texto: "Confie no Senhor quando precisar de ajuda." },
  { referencia: "Salmo 116:1-2", texto: "Ame a Deus e fale com ele com liberdade." },
  { referencia: "Salmo 117:1-2", texto: "Compartilhe o louvor e a gratidão." },
  { referencia: "Salmo 118:24", texto: "Hoje é um presente: viva com alegria e propósito." },
  { referencia: "Salmo 119:11", texto: "Guarde os ensinamentos de Deus no coração." },
  { referencia: "Salmo 120:1", texto: "Quando estiver angustiado, ore." },
  { referencia: "Salmo 121:1-2", texto: "Levante os olhos e lembre-se de onde vem seu socorro." },
  { referencia: "Salmo 122:1", texto: "Alegre-se por poder buscar a presença de Deus." },
  { referencia: "Salmo 123:1", texto: "Olhe para Deus com expectativa." },
  { referencia: "Salmo 124:8", texto: "Lembre-se de que sua ajuda vem do Criador." },
  { referencia: "Salmo 125:1", texto: "Confie em Deus com estabilidade." },
  { referencia: "Salmo 126:3", texto: "Reconheça as grandes coisas que Deus já fez." },
  { referencia: "Salmo 127:1", texto: "Construa seus projetos com Deus no centro." },
  { referencia: "Salmo 128:1", texto: "Caminhe com reverência e gratidão." },
  { referencia: "Salmo 129:4", texto: "Confie na justiça de Deus." },
  { referencia: "Salmo 130:5", texto: "Espere no Senhor e na sua palavra." },
  { referencia: "Salmo 131:2", texto: "Busque quietude interior diante de Deus." },
  { referencia: "Salmo 132:15", texto: "Receba o cuidado e a provisão de Deus." },
  { referencia: "Salmo 133:1", texto: "Valorize a união e a paz entre as pessoas." },
  { referencia: "Salmo 134:2", texto: "Levante suas mãos e seu coração em gratidão." },
  { referencia: "Salmo 135:3", texto: "Louve porque Deus é bom." },
  { referencia: "Salmo 136:1", texto: "Agradeça porque o amor de Deus permanece." },
  { referencia: "Salmo 137:5", texto: "Não esqueça aquilo que é importante para sua fé." },
  { referencia: "Salmo 138:3", texto: "Quando clamar, espere que Deus fortaleça você." },
  { referencia: "Salmo 139:14", texto: "Agradeça pela forma única como sua vida foi criada." },
  { referencia: "Salmo 140:13", texto: "Escolha viver de modo digno e agradecido." },
  { referencia: "Salmo 141:3", texto: "Peça sabedoria para falar no momento certo." },
  { referencia: "Salmo 142:5", texto: "Faça de Deus seu refúgio." },
  { referencia: "Salmo 143:8", texto: "Peça que o amor de Deus conduza seu dia desde a manhã." },
  { referencia: "Salmo 144:1-2", texto: "Reconheça Deus como sua proteção e força." },
  { referencia: "Salmo 145:18", texto: "Busque Deus com sinceridade; ele está perto." },
  { referencia: "Salmo 146:5", texto: "Feliz é quem encontra sua esperança no Senhor." },
  { referencia: "Salmo 147:3", texto: "Deus cuida de corações feridos." },
  { referencia: "Salmo 148:13", texto: "Reconheça a grandeza do nome de Deus." },
  { referencia: "Salmo 149:4", texto: "Deus se alegra com quem busca sua vontade." },
  { referencia: "Salmo 150:6", texto: "Que tudo em você encontre motivo para louvar." },
  { referencia: "Salmo 1:1-3", texto: "Comece o dia escolhendo caminhos que produzam bons frutos." },
  { referencia: "Salmo 2:12", texto: "Confie em Deus e encontre segurança nele." },
  { referencia: "Salmo 3:3", texto: "Deus pode ser seu escudo e sua força neste dia." },
  { referencia: "Salmo 4:8", texto: "Descanse em paz, sabendo que Deus cuida de você." },
  { referencia: "Salmo 5:11", texto: "Alegre-se na proteção e na bondade do Senhor." },
  { referencia: "Salmo 6:9", texto: "Deus ouve a oração sincera." },
  { referencia: "Salmo 7:10", texto: "Entregue sua causa a Deus e siga com confiança." },
  { referencia: "Salmo 8:3-4", texto: "Contemple a grandeza de Deus e lembre-se do seu valor." },
  { referencia: "Salmo 9:1-2", texto: "Agradeça pelas coisas boas que Deus já fez." },
  { referencia: "Salmo 10:17", texto: "Deus escuta os desejos de um coração humilde." },
  { referencia: "Salmo 11:7", texto: "Busque viver com justiça e integridade." },
  { referencia: "Salmo 12:6", texto: "A palavra de Deus é firme e confiável." },
  { referencia: "Salmo 13:5-6", texto: "Mesmo em dias difíceis, mantenha a confiança no amor de Deus." },
  { referencia: "Salmo 14:7", texto: "Espere pela restauração que vem do Senhor." },
  { referencia: "Salmo 15:1-2", texto: "Viva com sinceridade e pratique o que é correto." },
  { referencia: "Salmo 16:8", texto: "Mantenha Deus diante de você em cada decisão." },
  { referencia: "Salmo 17:8", texto: "Peça proteção e cuidado para o seu caminho." },
  { referencia: "Salmo 18:2", texto: "Faça de Deus seu refúgio e sua fortaleza." },
  { referencia: "Salmo 19:1", texto: "Veja a criação como sinal da grandeza de Deus." },
  { referencia: "Salmo 20:7", texto: "Não coloque sua confiança apenas nas coisas humanas." },
  { referencia: "Salmo 21:7", texto: "Quem confia em Deus encontra firmeza." },
  { referencia: "Salmo 22:26", texto: "Busque a Deus com humildade e gratidão." },
  { referencia: "Salmo 23:1", texto: "Deixe Deus conduzir cada necessidade do seu dia." },
  { referencia: "Salmo 24:1", texto: "Lembre-se de que tudo pertence ao Senhor." },
  { referencia: "Salmo 25:4-5", texto: "Peça direção e disposição para aprender os caminhos de Deus." },
  { referencia: "Salmo 26:3", texto: "Mantenha os olhos na fidelidade de Deus." },
  { referencia: "Salmo 27:1", texto: "Quando o medo aparecer, lembre-se de que Deus é luz." },
  { referencia: "Salmo 28:7", texto: "Fortaleça o coração confiando no Senhor." },
  { referencia: "Salmo 29:11", texto: "Receba a paz que Deus oferece." },
  { referencia: "Salmo 30:5", texto: "Depois da noite, a alegria pode voltar." },
  { referencia: "Salmo 31:24", texto: "Tenha coragem e mantenha a esperança." },
  { referencia: "Salmo 32:8", texto: "Deixe Deus orientar suas escolhas." },
  { referencia: "Salmo 33:20-22", texto: "Espere em Deus com confiança e gratidão." },
  { referencia: "Salmo 34:8", texto: "Experimente a bondade de Deus nas pequenas coisas." },
  { referencia: "Salmo 35:9", texto: "Faça de Deus a fonte da sua alegria." },
  { referencia: "Salmo 36:7", texto: "Acolha-se no amor e na misericórdia de Deus." },
  { referencia: "Salmo 37:5", texto: "Entregue seus planos ao Senhor e continue fazendo o bem." },
  { referencia: "Salmo 38:15", texto: "Mesmo esperando, mantenha sua esperança em Deus." },
  { referencia: "Salmo 39:7", texto: "Pergunte a si mesmo onde está sua verdadeira esperança." },
  { referencia: "Salmo 40:1", texto: "Espere com paciência; Deus não ignora sua oração." },
  { referencia: "Salmo 41:1", texto: "Pratique generosidade com quem precisa." },
  { referencia: "Salmo 42:11", texto: "Quando estiver abatido, volte a colocar sua esperança em Deus." },
  { referencia: "Salmo 43:3", texto: "Peça luz para enxergar o caminho correto." },
  { referencia: "Salmo 44:8", texto: "Que sua alegria esteja em Deus, não apenas nas circunstâncias." },
  { referencia: "Salmo 45:1", texto: "Use suas palavras para transmitir aquilo que é bom." },
  { referencia: "Salmo 46:1", texto: "Em tempos de dificuldade, Deus é um refúgio presente." },
  { referencia: "Salmo 47:1", texto: "Celebre com alegria as vitórias e bênçãos." },
  { referencia: "Salmo 48:14", texto: "Lembre-se de que Deus permanece presente em cada fase da vida." },
  { referencia: "Salmo 49:15", texto: "Confie que Deus pode resgatar e sustentar você." },
  { referencia: "Salmo 50:15", texto: "Clame a Deus quando precisar de ajuda." },
  { referencia: "Salmo 51:10", texto: "Peça um coração renovado e disposto a recomeçar." },
  { referencia: "Salmo 52:8", texto: "Permaneça firme como quem está plantado em Deus." },
  { referencia: "Salmo 53:6", texto: "Espere pela salvação e pela restauração do Senhor." },
  { referencia: "Salmo 54:4", texto: "Lembre-se de que Deus sustenta você." },
  { referencia: "Salmo 55:22", texto: "Entregue suas preocupações a Deus e não carregue tudo sozinho." },
  { referencia: "Salmo 56:3", texto: "Quando o medo vier, escolha confiar." },
  { referencia: "Salmo 57:7", texto: "Fortaleça seu coração antes de enfrentar os desafios." },
  { referencia: "Salmo 58:11", texto: "Continue fazendo o bem mesmo quando parecer difícil." },
  { referencia: "Salmo 59:16", texto: "Comece e termine o dia lembrando da fidelidade de Deus." },
  { referencia: "Salmo 60:12", texto: "Com Deus, você pode avançar com coragem." },
  { referencia: "Salmo 61:2-3", texto: "Quando estiver longe ou cansado, busque abrigo em Deus." },
  { referencia: "Salmo 62:1-2", texto: "Descanse em Deus antes de procurar respostas em todo lugar." },
  { referencia: "Salmo 63:1", texto: "Procure Deus com sede e sinceridade." },
  { referencia: "Salmo 64:10", texto: "Alegre-se em Deus e escolha viver com retidão." },
  { referencia: "Salmo 65:11", texto: "Reconheça as bênçãos que chegam ao longo do ano." },
];

const hoje = new Date();

const inicioAno = Date.UTC(hoje.getFullYear(), 0, 1);
const dataHoje = Date.UTC(
  hoje.getFullYear(),
  hoje.getMonth(),
  hoje.getDate()
);

const numeroDoDia = Math.floor(
  (dataHoje - inicioAno) / (1000 * 60 * 60 * 24)
);

const indice = numeroDoDia % salmos.length;
const salmo = salmos[indice];

document.getElementById("referencia").textContent = salmo.referencia;
document.getElementById("texto").textContent = salmo.texto;